#region

using CustomAttributes;

#endregion

namespace Characters.Assets
{
    // Portrait identity enum. Values are stable hashes auto-generated by [AddressableEnums] from the
    // portrait art folder. The enum is the network-serialized identity on Role.rolePortrait; the actual
    // Sprite is resolved in the view layer via a PortraitTable ScriptableObject (direct asset references),
    // replacing the former path-string + Addressables lookup.
    public static class CharacterPortraitsValues
    {
        [AddressableEnums("Assets/Art/Sprites/Portraits")]
        public enum CharacterPortraits
        {
            Abyss = 1048685107,
            ChasseuseDePrime = 890829750,
            DernierGardien = 1959347720,
            DrGloubi = 295621807,
            Dryade = 1970802544,
            Geolier = 1886328777,
            Incomplet = 1605640824,
            Moork = 403389003,
            ORIGINE = 1674237905,
            Orpheline = 1124117774,
            Prophete = 823899898,
            Repenti = 1256501025,
            Robot = 683198692,
            Technomancien = 632219777,
            Uges = 864506531,
            Vahal = 1384333719,
            Inconnu = 148354486,
            Messager = 883583601,
            LumaLaCroupiere = 787665622,
        }
    }
}
